//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVE
    {
        public int ID { get; set; }
        public int TASK_ID { get; set; }
        public string OBSERVE_ID { get; set; }
        public string ARCHIVECONTENT { get; set; }
        public string ARCHIVE_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_TIME { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual TASK TASK { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
