//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COEntities : DbContext
    {
        public COEntities()
            : base("name=COEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ARCHIVE> ARCHIVEs { get; set; }
        public DbSet<ATTACHMENT> ATTACHMENTs { get; set; }
        public DbSet<CLASS> CLASSes { get; set; }
        public DbSet<DISTRIBUT> DISTRIBUTs { get; set; }
        public DbSet<DOC> DOCs { get; set; }
        public DbSet<EVALUATE> EVALUATEs { get; set; }
        public DbSet<OBSERVE> OBSERVEs { get; set; }
        public DbSet<PERMISSION> PERMISSIONs { get; set; }
        public DbSet<ROLE> ROLEs { get; set; }
        public DbSet<SCHOOL> SCHOOLs { get; set; }
        public DbSet<STEP> STEPs { get; set; }
        public DbSet<STEP_SEL> STEP_SEL { get; set; }
        public DbSet<STYLE> STYLEs { get; set; }
        public DbSet<SUBJECT> SUBJECTs { get; set; }
        public DbSet<TARGET> TARGETs { get; set; }
        public DbSet<TARGET_SEL> TARGET_SEL { get; set; }
        public DbSet<TASK> TASKs { get; set; }
        public DbSet<TITLE> TITLEs { get; set; }
        public DbSet<USER> USERs { get; set; }
        public DbSet<USER_TASK> USER_TASK { get; set; }
    }
}
