//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUT
    {
        public int ID { get; set; }
        public int DISTRIBUT_ID { get; set; }
        public long DISTRIBUT_SEQ_ID { get; set; }
        public string OBSERVER_ID { get; set; }
        public string OBSERVER_N { get; set; }
        public Nullable<bool> RECEIVE { get; set; }
        public Nullable<System.DateTime> RECEIVE_TIME { get; set; }
        public Nullable<bool> OBSERVE { get; set; }
        public Nullable<System.DateTime> OBSERVE_TIME { get; set; }
        public Nullable<bool> UPLOAD { get; set; }
        public Nullable<System.DateTime> UPLOAD_TIME { get; set; }
        public Nullable<bool> FILING { get; set; }
        public Nullable<System.DateTime> FILING_TIME { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
