//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC
    {
        public int ID { get; set; }
        public int DOC_ID { get; set; }
        public long DOC_SEQ_ID { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_N { get; set; }
        public string DOC_TYPE { get; set; }
        public string DOC_FILE { get; set; }
    }
}
