//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STEP
    {
        public STEP()
        {
            this.ATTACHMENTs = new HashSet<ATTACHMENT>();
            this.OBSERVEs = new HashSet<OBSERVE>();
            this.STEP_SEL = new HashSet<STEP_SEL>();
        }
    
        public int ID { get; set; }
        public string STEP_ID { get; set; }
        public string STEP_NAME { get; set; }
        public string STEP_N { get; set; }
        public string STEP_TYPE { get; set; }
    
        public virtual ICollection<ATTACHMENT> ATTACHMENTs { get; set; }
        public virtual ICollection<OBSERVE> OBSERVEs { get; set; }
        public virtual ICollection<STEP_SEL> STEP_SEL { get; set; }
    }
}
