//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARGET_SEL
    {
        public int ID { get; set; }
        public int TARGET_SEL_ID { get; set; }
        public long TARGET_SEQ_ID { get; set; }
        public string TARGET_ID { get; set; }
        public string TARGET_SUBID { get; set; }
        public string TARGET_SUBID2 { get; set; }
        public string TARGET_N { get; set; }
    
        public virtual TARGET TARGET { get; set; }
    }
}
