//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        public TASK()
        {
            this.ARCHIVEs = new HashSet<ARCHIVE>();
            this.ATTACHMENTs = new HashSet<ATTACHMENT>();
            this.OBSERVEs = new HashSet<OBSERVE>();
        }
    
        public int ID { get; set; }
        public int TASK_ID { get; set; }
        public string TASK_NAME { get; set; }
        public string SCHOOL_ID { get; set; }
        public string SCHOOL_N { get; set; }
        public string SUBJECT_ID { get; set; }
        public string SUBJECT_N { get; set; }
        public string TITLE_ID { get; set; }
        public string TITLE_N { get; set; }
        public string STYLE_ID { get; set; }
        public string STYLE_N { get; set; }
        public string CLASS_ID { get; set; }
        public string CLASS_N { get; set; }
        public string TEACHER_ID { get; set; }
        public string TEACHER_N { get; set; }
        public int DOC_ID { get; set; }
        public int STEP_SEL_ID { get; set; }
        public int TARGET_SEL_ID { get; set; }
        public int DISTRIBUT_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public Nullable<int> RECEIVE { get; set; }
        public Nullable<System.DateTime> RECEIVE_TIME { get; set; }
        public Nullable<int> OBSERVE { get; set; }
        public Nullable<System.DateTime> OBSERVE_TIME { get; set; }
        public Nullable<int> UPLOAD { get; set; }
        public Nullable<System.DateTime> UPLOAD_TIME { get; set; }
        public string FILING { get; set; }
        public Nullable<System.DateTime> FILING_TIME { get; set; }
    
        public virtual ICollection<ARCHIVE> ARCHIVEs { get; set; }
        public virtual ICollection<ATTACHMENT> ATTACHMENTs { get; set; }
        public virtual CLASS CLASS { get; set; }
        public virtual ICollection<OBSERVE> OBSERVEs { get; set; }
        public virtual STYLE STYLE { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
        public virtual TITLE TITLE { get; set; }
        public virtual USER USER { get; set; }
    }
}
