//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.ARCHIVEs = new HashSet<ARCHIVE>();
            this.ARCHIVEs1 = new HashSet<ARCHIVE>();
            this.ATTACHMENTs = new HashSet<ATTACHMENT>();
            this.DISTRIBUTs = new HashSet<DISTRIBUT>();
            this.OBSERVEs = new HashSet<OBSERVE>();
            this.TASKs = new HashSet<TASK>();
        }
    
        public int ID { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_N { get; set; }
        public string USER_TYPE { get; set; }
        public string USER_PWD { get; set; }
        public string USER_AREA { get; set; }
        public string USER_SCHOOL { get; set; }
        public string USER_SUBJECT { get; set; }
    
        public virtual ICollection<ARCHIVE> ARCHIVEs { get; set; }
        public virtual ICollection<ARCHIVE> ARCHIVEs1 { get; set; }
        public virtual ICollection<ATTACHMENT> ATTACHMENTs { get; set; }
        public virtual ICollection<DISTRIBUT> DISTRIBUTs { get; set; }
        public virtual ICollection<OBSERVE> OBSERVEs { get; set; }
        public virtual ICollection<TASK> TASKs { get; set; }
    }
}
